---
- hosts: do
  vars_files:
    - vars/default.yml

  tasks:
    - name: Clone repository
      git:
        repo: "{{ repository_url }}"
        dest: "{{ repository_clone_path }}"

    - name: Copy environment variables (.env) files to repository
      copy:
        src: "{{ env_file_path_docker }}"
        dest: "{{ repository_clone_path }}/.env"
