---
- hosts: localhost
  connection: local
  vars_files:
    - vars/default.yml

  tasks:
    - name: Create an SSH Key Pair
      openssh_keypair:
        path: "{{ ssh_keys_path_docker }}/id_rsa"

    - name: Upload SSH Key to Digital Ocean
      digital_ocean_sshkey:
        name: "{{ digital_ocean_ssh_key_name }}"
        ssh_pub_key: "{{ lookup('file', ssh_keys_path_docker + '/id_rsa.pub') }}"
        state: present
      register: docker_ssh_key

    - name: Create Digital Ocean Droplet
      digital_ocean_droplet:
        unique_name: yes # "yes" makes it idempotent
        region: "{{ digital_ocean_region }}"
        image: "{{ digital_ocean_image }}"
        size_id: "{{ digital_ocean_image_size_id }}"
        wait: yes
        name: "{{ digital_ocean_droplet_name }}"
        state: present
        ssh_keys: [ "{{ docker_ssh_key.data.ssh_key.id }}" ]
      register: created_droplet

    - name: Tag Digital Ocean Droplet
      digital_ocean_tag:
        name: "{{ digital_ocean_image_tag }}"
        resource_id: "{{ created_droplet.data.droplet.id }}"
        state: present
      register: tag_response

    - name: Add Droplet to "do" host
      add_host:
        name: "{{ created_droplet.data.ip_address }}"
        groups: "do"

    - name: Wait for SSH to come up
      local_action: wait_for host={{ created_droplet.data.ip_address }} port=22 delay=10 timeout=320 state=started
