---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/default.yml

  tasks:
    - openssh_keypair:
        path: /tmp/id_ssh_rsa

    - name: "Create ssh key"
      digital_ocean_sshkey:
        name: "ansible-tutorial-ssh-key"
        ssh_pub_key: "{{ lookup('file', '/tmp/id_ssh_rsa.pub') }}"
        state: present
      register: docker_ssh_key

    - digital_ocean_droplet:
        unique_name: yes # "yes" makes it idempotent
        region: nyc3
        image: ubuntu-20-04-x64
        size_id: s-1vcpu-1gb
        wait: yes
        name: "{{ droplet_name }}"
        state: present
        ssh_keys: [ "{{ docker_ssh_key.data.ssh_key.id }}" ]
      register: created_droplet

    - digital_ocean_tag:
        name: ansible-tutorial-django
        resource_id: "{{ created_droplet.data.droplet.id }}"
        state: present
      register: tag_response

    - name: add hosts
      add_host:
        name: "{{ created_droplet.data.ip_address }}"
        groups: "do"
