---
- import_playbook: playbooks/digital_ocean_droplet.yml
- import_playbook: playbooks/docker_setup.yml
- import_playbook: playbooks/clone_repository.yml
- import_playbook: playbooks/compose_start.yml
